name: Publish repository content to website

on:
  push:
    paths:
    - '.github/workflows/**'
    - 'presentation/**'
    - 'azure/**'
    - 'docker/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Login to CLI
      run: az login --service-principal -u ${{ secrets.SPN_ID }} -p ${{ secrets.SPN_KEY }} --tenant ${{ secrets.SPN_TENANT }} -o none

    - name: Configure CLI
      run: az extension add --name storage-preview

    - name: Upload files
      run: az storage blob directory upload -c "$web/web" --account-name greet -s ${GITHUB_WORKSPACE}/presentation -d directory --recursive
